### ISSUE TITLE
Allow injection of `final` for use in switches

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/d1to2fix#18]
It's very common to need `final switch`. Allowing it to be injected in D2 builds would be really useful for stage 2 projects.

**Comment by mihails-strasuns-sociomantic** [comment]
Holding this a bit until @mathias-lang-sociomantic attempts his D1 compiler tweak to allow and ignore `final` in such contexts as that would allow for a cleaner transition.

**Comment by mathias-lang-sociomantic** [comment]
Oh right, allmost forgot about this:
https://github.com/dlang/dmd/pull/6833

**Comment by mihails-strasuns-sociomantic** [comment]
Closed in favor of dmd1 solution
